<template><div><h1 id="deposits" tabindex="-1"><a class="header-anchor" href="#deposits" aria-hidden="true">#</a> Deposits</h1>
<br>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>The main reason for extending the Kele Pool network is to implement custom deposit logic which funnels user deposits into the deposit pool.
For example, a fund manager may wish to stake their users' ETH in Kele Pool via their own smart contracts, and abstract the use of Kele Pool itself away from their users.</p>
<p><strong>Note:</strong> the <code v-pre>RocketDepositPool</code> contract address should <em>not</em> be hard-coded in your contracts, but retrieved from <code v-pre>RocketStorage</code> dynamically.
See <a href="ADD_URL_HERE">Interacting With Kele Pool</a> for more details.</p>
<br>
<h2 id="implementation" tabindex="-1"><a class="header-anchor" href="#implementation" aria-hidden="true">#</a> Implementation</h2>
<p>The following describes a basic example contract which forwards deposited ETH into Kele Pool and minted rETH back to the caller::</p>
<div class="language-solidity ext-solidity line-numbers-mode"><pre v-pre class="language-solidity"><code><span class="token keyword">import</span> <span class="token string">"RocketStorageInterface.sol"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string">"RocketDepositPoolInterface.sol"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string">"RocketTokenRETHInterface.sol"</span><span class="token punctuation">;</span>

<span class="token keyword">contract</span> <span class="token class-name">Example</span> <span class="token punctuation">{</span>

    RocketStorageInterface rocketStorage <span class="token operator">=</span> <span class="token function">RocketStorageInterface</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    <span class="token keyword">constructor</span><span class="token punctuation">(</span><span class="token builtin">address</span> _rocketStorageAddress<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        rocketStorage <span class="token operator">=</span> <span class="token function">RocketStorageInterface</span><span class="token punctuation">(</span>_rocketStorageAddress<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token function">receive</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token keyword">external</span> <span class="token keyword">payable</span> <span class="token punctuation">{</span>
        <span class="token comment">// Check deposit amount</span>
        <span class="token keyword">require</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span>value <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">"Invalid deposit amount"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// Load contracts</span>
        <span class="token builtin">address</span> rocketDepositPoolAddress <span class="token operator">=</span> rocketStorage<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token function">keccak256</span><span class="token punctuation">(</span>abi<span class="token punctuation">.</span><span class="token function">encodePacked</span><span class="token punctuation">(</span><span class="token string">"contract.address"</span><span class="token punctuation">,</span> <span class="token string">"rocketDepositPool"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        RocketDepositPoolInterface rocketDepositPool <span class="token operator">=</span> <span class="token function">RocketDepositPoolInterface</span><span class="token punctuation">(</span>rocketDepositPoolAddress<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token builtin">address</span> rocketTokenRETHAddress <span class="token operator">=</span> rocketStorage<span class="token punctuation">.</span><span class="token function">getAddress</span><span class="token punctuation">(</span><span class="token function">keccak256</span><span class="token punctuation">(</span>abi<span class="token punctuation">.</span><span class="token function">encodePacked</span><span class="token punctuation">(</span><span class="token string">"contract.address"</span><span class="token punctuation">,</span> <span class="token string">"rocketTokenRETH"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        RocketTokenRETHInterface rocketTokenRETH <span class="token operator">=</span> <span class="token function">RocketTokenRETHInterface</span><span class="token punctuation">(</span>rocketTokenRETHAddress<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// Forward deposit to RP &amp; get amount of rETH minted</span>
        <span class="token builtin">uint256</span> rethBalance1 <span class="token operator">=</span> rocketTokenRETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token builtin">address</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        rocketDepositPool<span class="token punctuation">.</span>deposit<span class="token punctuation">{</span>value<span class="token punctuation">:</span> msg<span class="token punctuation">.</span>value<span class="token punctuation">}</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token builtin">uint256</span> rethBalance2 <span class="token operator">=</span> rocketTokenRETH<span class="token punctuation">.</span><span class="token function">balanceOf</span><span class="token punctuation">(</span><span class="token builtin">address</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">require</span><span class="token punctuation">(</span>rethBalance2 <span class="token operator">></span> rethBalance1<span class="token punctuation">,</span> <span class="token string">"No rETH was minted"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token builtin">uint256</span> rethMinted <span class="token operator">=</span> rethBalance2 <span class="token operator">-</span> rethBalance1<span class="token punctuation">;</span>
        <span class="token comment">// Transfer rETH to caller</span>
        <span class="token keyword">require</span><span class="token punctuation">(</span>rocketTokenRETH<span class="token punctuation">.</span><span class="token function">transfer</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span>sender<span class="token punctuation">,</span> rethMinted<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">"rETH was not transferred to caller"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
