<template><div><h1 id="javascript" tabindex="-1"><a class="header-anchor" href="#javascript" aria-hidden="true">#</a> Javascript</h1>
<h2 id="introduction" tabindex="-1"><a class="header-anchor" href="#introduction" aria-hidden="true">#</a> Introduction</h2>
<p>The Kele Pool JavaScript library is the primary means of interaction with the Kele Pool network for users and applications. It is used by applications such as the Kele Pool website to retrieve information about the network and facilitate user interaction. It provides wrapper methods which load the Kele Pool contracts with web3.js and abstractions to use many of their features easily.</p>
<p>This guide assumes familiarity with JavaScript and provides all code samples as JS.</p>
<h2 id="getting-started" tabindex="-1"><a class="header-anchor" href="#getting-started" aria-hidden="true">#</a> Getting Started</h2>
<h3 id="installation" tabindex="-1"><a class="header-anchor" href="#installation" aria-hidden="true">#</a> Installation</h3>
<p>The Kele Pool JavaScript library can be added to your application via NPM, and requires <a href="https://github.com/ethereum/web3.js/" target="_blank" rel="noopener noreferrer">web3.js<ExternalLinkIcon/></a>:</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">npm</span> <span class="token function">install</span> @kelepool/api
<span class="token function">npm</span> <span class="token function">install</span> web3
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="initialization" tabindex="-1"><a class="header-anchor" href="#initialization" aria-hidden="true">#</a> Initialization</h3>
<p>The library must be initialized with a web3 instance and a <a href="https://github.com/trufflesuite/truffle" target="_blank" rel="noopener noreferrer">Truffle<ExternalLinkIcon/></a> <code v-pre>RocketStorage</code> contract artifact:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> Web3 <span class="token keyword">from</span> <span class="token string">'web3'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> RocketPool <span class="token keyword">from</span> <span class="token string">'kelepool'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> RocketStorage <span class="token keyword">from</span> <span class="token string">'./contracts/RocketStorage.json'</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> web3 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Web3</span><span class="token punctuation">(</span><span class="token string">'http://localhost:8545'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> rp <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RocketPool</span><span class="token punctuation">(</span>web3<span class="token punctuation">,</span> RocketStorage<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Alternatively you can also initialize it using a Contract Storage Address:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> Web3 <span class="token keyword">from</span> <span class="token string">'web3'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> RocketPool <span class="token keyword">from</span> <span class="token string">'kelepool'</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> web3 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Web3</span><span class="token punctuation">(</span><span class="token string">'http://localhost:8545'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> RocketStorage <span class="token operator">=</span> <span class="token string">"0xd8Cd47263414aFEca62d6e2a3917d6600abDceB3"</span><span class="token punctuation">;</span> <span class="token comment">// Current Testnet Storage Contract</span>
<span class="token keyword">const</span> rp <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RocketPool</span><span class="token punctuation">(</span>web3<span class="token punctuation">,</span> RocketStorage<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="usage" tabindex="-1"><a class="header-anchor" href="#usage" aria-hidden="true">#</a> Usage</h3>
<p>The Kele Pool library is divided into several modules, each for interacting with a different aspect of the network:</p>
<ul>
<li><code v-pre>auction</code>: Handles interactions with Auctions</li>
<li><code v-pre>contracts</code>: Handles dynamic loading of the Kele Pool contracts</li>
<li><code v-pre>deposit</code>: Handles user deposits</li>
<li><code v-pre>dao</code>: Handles DAO related interactions</li>
<li><code v-pre>minipool</code>: Manages minipools in the Kele Pool network</li>
<li><code v-pre>network</code>: Handles miscellaneous network functionality</li>
<li><code v-pre>node</code>: Manages the nodes making up the Kele Pool network</li>
<li><code v-pre>rewards</code>: Handles interactions with rewards</li>
<li><code v-pre>settings</code>: Provides information on settings</li>
<li><code v-pre>tokens</code>: Manages token interactions</li>
<li><code v-pre>vault</code>: Handles interactions with the vault</li>
</ul>
<p>All methods typically return promises due to the asynchronous nature of working with the Ethereum network. Getters return promises which resolve to their value, while mutators (methods which send transactions) return promises which resolve to a transaction receipt. Mutators also accept a transaction options object, and an <code v-pre>onConfirmation</code> callback handler to handle specific confirmation numbers on transactions.</p>
<p>When using the Kele Pool library in your project, you may handle the promises returned in the traditional way, or use async/await syntax if supported, e.g.:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>rp<span class="token punctuation">.</span>contracts<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'rocketDepositPool'</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">rocketDepositPool</span> <span class="token operator">=></span> rocketDepositPool<span class="token punctuation">.</span>methods<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">balance</span> <span class="token operator">=></span> <span class="token punctuation">{</span> console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>balance<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>or:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> rocketDepositPool <span class="token operator">=</span> <span class="token keyword">await</span> rp<span class="token punctuation">.</span>contracts<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'rocketDepositPool'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">let</span> balance <span class="token operator">=</span> <span class="token keyword">await</span> rocketDepositPool<span class="token punctuation">.</span>methods<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>balance<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="contracts" tabindex="-1"><a class="header-anchor" href="#contracts" aria-hidden="true">#</a> Contracts</h2>
<h3 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h3>
<p>The <code v-pre>contracts</code> module loads Kele Pool contract ABIs and addresses from <code v-pre>RocketStorage</code>, where all network contracts are registered. Contract ABIs and addresses are loaded from the chain, the ABIs are decompressed and decoded, and then web3 contract instances are created from them. This is performed dynamically because Kele Pool contracts can be upgraded and their ABIs and addresses may change.</p>
<p>This module is used by other library modules internally, and generally does not need to be used directly. However, it is exposed publicly for when direct access to web3 contract instances is desired, or the library wrapper methods are insufficient.</p>
<h3 id="loading-contracts-abis" tabindex="-1"><a class="header-anchor" href="#loading-contracts-abis" aria-hidden="true">#</a> Loading Contracts &amp; ABIs</h3>
<p>Network contracts can be loaded via the <code v-pre>contracts.get()</code> method, which accepts either a single contract name as a string, or a list of contract names as an array of strings. If a single contract name is passed, this method returns a promise resolving to a web3 contract instance. If a list of contract names is passed, it returns a promise resolving to an array of web3 contract instances, in the same order.</p>
<p>Contract addresses and ABIs can be loaded in a similar fashion via the <code v-pre>contracts.address()</code> and <code v-pre>contracts.abi()</code> methods, which accept either a single contract name, or a list of names, to retrieve data for.</p>
<h3 id="creating-contract-instances" tabindex="-1"><a class="header-anchor" href="#creating-contract-instances" aria-hidden="true">#</a> Creating Contract Instances</h3>
<p>Some network contracts, such as <code v-pre>RocketMinipool</code>, have multiple instances deployed at a number of different addresses. To create an instance of one of these contracts, use the <code v-pre>contracts.make(name, address)</code> method. It accepts the name of the contract and the address of the specific instance required, both as strings, and returns a promise resolving to a web3 contract instance.</p>
<h3 id="alternate-contract-versions" tabindex="-1"><a class="header-anchor" href="#alternate-contract-versions" aria-hidden="true">#</a> Alternate Contract Versions</h3>
<p>When Kele Pool network contracts are upgraded, old versions remain on the chain and can still be accessed if required. A “contract version set”, consisting of all versions of a contract by name, can be loaded with the <code v-pre>contracts.versions(name)</code> method. This method accepts the name of the contract to load, and returns a promise resolving to the version set object.</p>
<p>Contract version sets are primarily used for accessing old event data. They provide the following methods:</p>
<ul>
<li><code v-pre>versionSet.current()</code>: Returns the current version of the contract</li>
<li><code v-pre>versionSet.first()</code>: Returns the first version of the contract deployed</li>
<li><code v-pre>versionSet.at(index)</code>: Returns the version of the contract at the specified version index (0 = first version)</li>
<li><code v-pre>versionSet.getPastEvents(eventName, options)</code>: As per <a href="https://web3js.readthedocs.io/en/v1.2.1/web3-eth-contract.html#getpastevents" target="_blank" rel="noopener noreferrer">web3’s contract.getPastEvents<ExternalLinkIcon/></a>, but returns a promise resolving to the events for all versions of the contract</li>
</ul>
<h2 id="api-reference" tabindex="-1"><a class="header-anchor" href="#api-reference" aria-hidden="true">#</a> API Reference</h2>
<p>For more information and examples please review the <RouterLink to="/zh/developers/api/js/RocketPool.html#constructors">API Reference.</RouterLink></p>
</div></template>
