export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":""},["/index.html","/index.md"]],
  ["v-2d0ad528","/zh/",{"title":""},["/zh/index.html","/zh/index.md"]],
  ["v-1da60d3e","/zh/developers/",{"title":"开发者文档"},["/zh/developers/index.html","/zh/developers/README.md"]],
  ["v-2c726a57","/zh/wiki/",{"title":"Pow"},["/zh/wiki/index.html","/zh/wiki/README.md"]],
  ["v-c10bf020","/zh/guides/",{"title":"总览"},["/zh/guides/index.html","/zh/guides/README.md"]],
  ["v-2d86aa39","/en/developers/",{"title":"Developer documentation"},["/en/developers/index.html","/en/developers/README.md"]],
  ["v-3741c0dc","/en/wiki/",{"title":"Pow"},["/en/wiki/index.html","/en/wiki/README.md"]],
  ["v-0f0e5a6b","/en/guides/",{"title":"Guides Overview"},["/en/guides/index.html","/en/guides/README.md"]],
  ["v-7e2bff32","/zh/wiki/pos/",{"title":"Pow"},["/zh/wiki/pos/index.html","/zh/wiki/pos/README.md"]],
  ["v-7e2bffae","/zh/wiki/pow/",{"title":"文章百科"},["/zh/wiki/pow/index.html","/zh/wiki/pow/README.md"]],
  ["v-54ed91b2","/en/developers/mina/",{"title":"Mina Network"},["/en/developers/mina/index.html","/en/developers/mina/README.md"]],
  ["v-3b3bb448","/en/developers/platon/",{"title":"PlatON Network"},["/en/developers/platon/index.html","/en/developers/platon/README.md"]],
  ["v-59f59f69","/en/wiki/pow/",{"title":"文章百科"},["/en/wiki/pow/index.html","/en/wiki/pow/README.md"]],
  ["v-59f59eed","/en/wiki/pos/",{"title":"Pow"},["/en/wiki/pos/index.html","/en/wiki/pos/README.md"]],
  ["v-3d4f70d2","/zh/developers/mina/api/",{"title":"API Reference"},["/zh/developers/mina/api/index.html","/zh/developers/mina/api/README.md"]],
  ["v-19049c70","/zh/developers/ethereum/contracts/",{"title":"如何调用智能合约质押？"},["/zh/developers/ethereum/contracts/index.html","/zh/developers/ethereum/contracts/README.md"]],
  ["v-176e33ef","/zh/developers/ethereum/api/",{"title":"如何查询用户质押信息？"},["/zh/developers/ethereum/api/index.html","/zh/developers/ethereum/api/README.md"]],
  ["v-72338c60","/zh/developers/ethereum/introductions/",{"title":"什么是ETH2.0质押？"},["/zh/developers/ethereum/introductions/index.html","/zh/developers/ethereum/introductions/README.md"]],
  ["v-02531178","/zh/developers/platon/api/",{"title":"API Reference"},["/zh/developers/platon/api/index.html","/zh/developers/platon/api/README.md"]],
  ["v-6edfc6d4","/en/developers/ethereum/api/",{"title":"How to query user staking information?"},["/en/developers/ethereum/api/index.html","/en/developers/ethereum/api/README.md"]],
  ["v-5c267626","/en/developers/ethereum/contracts/",{"title":"How to use smart contract to stake?"},["/en/developers/ethereum/contracts/index.html","/en/developers/ethereum/contracts/README.md"]],
  ["v-38c59b16","/en/developers/ethereum/introductions/",{"title":"What is ETH2.0 staking?"},["/en/developers/ethereum/introductions/index.html","/en/developers/ethereum/introductions/README.md"]],
  ["v-1b2dd608","/en/developers/mina/api/",{"title":"API Reference"},["/en/developers/mina/api/index.html","/en/developers/mina/api/README.md"]],
  ["v-1266199d","/en/developers/platon/api/",{"title":"API Reference"},["/en/developers/platon/api/index.html","/en/developers/platon/api/README.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
