export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":""},["/index.html","/index.md"]],
  ["v-ba934fd8","/config/",{"title":"Config"},["/config/index.html","/config/README.md"]],
  ["v-2549d2cd","/developers/",{"title":"Developer Documentation"},["/developers/index.html","/developers/README.md"]],
  ["v-ff762602","/guides/",{"title":"Guides Overview"},["/guides/index.html","/guides/README.md"]],
  ["v-2d0ad528","/zh/",{"title":""},["/zh/index.html","/zh/index.md"]],
  ["v-49c4cfc6","/guides/testnet/overview.html",{"title":"Practicing with the Test Network"},["/guides/testnet/overview","/guides/testnet/overview.md"]],
  ["v-7e370323","/guides/testnet/upgrading.html",{"title":"Migrating the Smartnode from Previous Beta Tests"},["/guides/testnet/upgrading","/guides/testnet/upgrading.md"]],
  ["v-7c2919f6","/zh/config/",{"title":"Config"},["/zh/config/index.html","/zh/config/README.md"]],
  ["v-1da60d3e","/zh/developers/",{"title":"Developer Documentation"},["/zh/developers/index.html","/zh/developers/README.md"]],
  ["v-c10bf020","/zh/guides/",{"title":"Guides Overview"},["/zh/guides/index.html","/zh/guides/README.md"]],
  ["v-65b120c1","/developers/usage/contracts/contracts.html",{"title":"Smart Contracts"},["/developers/usage/contracts/contracts","/developers/usage/contracts/contracts.md"]],
  ["v-11663b4a","/developers/usage/contracts/deposits.html",{"title":"Deposits"},["/developers/usage/contracts/deposits","/developers/usage/contracts/deposits.md"]],
  ["v-30182192","/developers/usage/contracts/design.html",{"title":"Contract Design & Upgradability"},["/developers/usage/contracts/design","/developers/usage/contracts/design.md"]],
  ["v-4544d865","/developers/usage/js/js.html",{"title":"Javascript"},["/developers/usage/js/js","/developers/usage/js/js.md"]],
  ["v-103d2468","/zh/guides/testnet/overview.html",{"title":"Practicing with the Test Network"},["/zh/guides/testnet/overview","/zh/guides/testnet/overview.md"]],
  ["v-0c243958","/zh/guides/testnet/upgrading.html",{"title":"Migrating the Smartnode from Previous Beta Tests"},["/zh/guides/testnet/upgrading","/zh/guides/testnet/upgrading.md"]],
  ["v-1ce810d6","/zh/developers/usage/js/js.html",{"title":"Javascript"},["/zh/developers/usage/js/js","/zh/developers/usage/js/js.md"]],
  ["v-4d2c3f72","/zh/developers/usage/contracts/contracts.html",{"title":"Smart Contracts"},["/zh/developers/usage/contracts/contracts","/zh/developers/usage/contracts/contracts.md"]],
  ["v-178aa98a","/zh/developers/usage/contracts/deposits.html",{"title":"Deposits"},["/zh/developers/usage/contracts/deposits","/zh/developers/usage/contracts/deposits.md"]],
  ["v-f3a82efe","/zh/developers/usage/contracts/design.html",{"title":"Contract Design & Upgradability"},["/zh/developers/usage/contracts/design","/zh/developers/usage/contracts/design.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
